sudo: false

language: java

jdk:
  - oraclejdk8

install: ./gradlew --version

script: 
  - ./gradlew --continue build
  - if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X} != X ]; then ./gradlew --continue release; fi

cache:
  directories:
  - "$HOME/.gradle"
